from collections import OrderedDict
PROVINCE_DEFINE = OrderedDict({"Beijing":"1、北京市",
                   "Tianjin":"2、天津市",
                   "Shanghai":"3、上海市",
                   "Chongqing":"4、重庆市",
                   "Heilongjiang":"5、黑龙江省",
                   "Jilin":"6、吉林省",
                   "Liaoning":"7、辽宁省",
                   "Hebei":"8、河北省",
                   "Neimenggu":"9、内蒙古自治区",
                   "Shanxi":"10、山西省",
                   "Shandong":"11、山东省",
                   "Henan":"12、河南省",
                   "Anhui":"13、安徽省",
                   "Jiangsu":"14、江苏省",
                   "Zhejiang":"15、浙江省",
                   "Fujian":"16、福建省",
                   "Jiangxi":"17、江西省",
                   "Guangdong":"18、广东省",
                   "Hubei":"19、湖北省",
                   "Hunan":"20、湖南省",
                   "Guangxi":"21、广西壮族自治区",
                   "Hainan":"22、海南省",
                   "Yunnan":"23、云南省",
                   "Guizhou":"24、贵州省",
                   "Sichuan":"25、四川省",
                   "ShanVxi":"26、陕西省",
                   "Ningxia":"27、宁夏回族自治区",
                   "Gansu":"28、甘肃省",
                   "Xizhang":"29、西藏自治区",
                   "Qinghai":"30、青海省",
                   "Xinjiang":"31、新疆维吾尔族自治区",
                   "Xianggang":"32、香港特别行政区",
                   "Aomen":"33、澳门特别行政区",
                   "Taiwan":"34、台湾省",
                   "XinjiangSCJSBT":"35、新疆生产建设兵团",
                  })
THIS_YEAR_TAG = '2018'

FILE_STORAGE_ROOT = '/var/django_projects/file_upload'
TABLE_NEED_FILE   = ['table1','table10','table11','table14','table16']
