# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
