# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swcworks_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWTable1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=256, null=True, verbose_name='文件名称')),
                ('doc_number', models.CharField(max_length=256, null=True, verbose_name='发文文号')),
                ('release_unit', models.CharField(max_length=256, null=True, verbose_name='发文单位')),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发文时间')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable10',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=256, null=True, verbose_name='文件名称')),
                ('doc_number', models.CharField(max_length=256, null=True, verbose_name='发文文号')),
                ('release_unit', models.CharField(max_length=256, null=True, verbose_name='发文单位')),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发文时间')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable11',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '省级'), (2, '地市级'), (3, '县区级')], null=True, verbose_name='级别')),
                ('area_name', models.CharField(max_length=64, null=True, verbose_name='地区名称')),
                ('shtt', models.IntegerField(null=True, verbose_name='社会团体')),
                ('shfwjg', models.IntegerField(null=True, verbose_name='社会服务机构')),
                ('jjh', models.IntegerField(null=True, verbose_name='基金会')),
                ('zyfwzzs', models.IntegerField(null=True, verbose_name='单位和社区内部成立的志愿服务组织数（个）')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable12',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('zczyzzs', models.IntegerField(null=True, verbose_name='注册志愿者总数（人）')),
                ('bl', models.IntegerField(null=True, verbose_name='注册志愿者占当地居民人口总数的比例（%）')),
                ('qg_zyzs', models.IntegerField(null=True, verbose_name='在全国志愿服务信息系统中的注册志愿者数（人）')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable13',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('jbdw', models.CharField(max_length=256, null=True, verbose_name='举办单位')),
                ('pxbmc', models.CharField(max_length=256, null=True, verbose_name='培训班名称')),
                ('pxlr', models.TextField(null=True, verbose_name='培训内容')),
                ('pxrs', models.IntegerField(null=True, verbose_name='培训人数')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable14',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=256, null=True, verbose_name='出台志愿服务记录实施方案的地区名称')),
                ('xsl', models.IntegerField(null=True, verbose_name='县（市、区）数量')),
                ('jsl', models.IntegerField(null=True, verbose_name='街（镇）数量')),
                ('sqsl', models.IntegerField(null=True, verbose_name='社区数量')),
                ('dwsl', models.IntegerField(null=True, verbose_name='单位数量')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable15',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('zyfwzss', models.IntegerField(null=True, verbose_name='志愿服务总时数（小时）')),
                ('nzyfwss', models.IntegerField(null=True, verbose_name='其中：2017年志愿服务时数（小时）')),
                ('zdzyfwhd', models.TextField(default='', verbose_name='省级重点志愿服务活动名称及简介')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable16',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('zyzccs', models.TextField(null=True, verbose_name='本地区激励保障志愿者的主要政策措施')),
                ('czzjtr', models.IntegerField(null=True, verbose_name='2017年财政资金投入')),
                ('fcjtr', models.IntegerField(null=True, verbose_name='2017年福彩金投入')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable17',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '省级层面'), (2, '全省总计投入资金')], null=True, verbose_name='统计层面')),
                ('czxzj', models.IntegerField(null=True, verbose_name='2017年财政性资金（万元）')),
                ('cpgyj', models.IntegerField(null=True, verbose_name='2017年彩票公益金（万元）')),
                ('qtzj', models.IntegerField(null=True, verbose_name='2017年其他资金（万元）')),
                ('qtzj_comments', models.TextField(null=True, verbose_name='2017年其他资金来源备注')),
                ('zjtr_total', models.IntegerField(null=True, verbose_name='2017年总计投入（万元）')),
                ('zfgm', models.IntegerField(null=True, verbose_name='其中：政府购买志愿服务运营管理的资金（万元）')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=512, null=True, verbose_name='地区和机构名称')),
                ('level', models.IntegerField(choices=[(1, '省级'), (2, '地市级'), (3, '县区级')], null=True, verbose_name='级别')),
                ('inst_type', models.IntegerField(choices=[(1, '编制管理部门批准设立的社会工作处（科、股）'), (2, '内部设立相对独立的社会工作处（科、股）'), (3, '在相关处（科、股）加挂社会工作处（科、股）牌子'), (4, '成立社会工作事业单位')], null=True, verbose_name='类别')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('t3_type', models.IntegerField(choices=[(1, '乡镇、街道和社区'), (2, '行政机关'), (3, '民政事业单位'), (4, '民政部门作为业务主管单位的社会组织'), (5, '其他（请注明）')], null=True, verbose_name='类别')),
                ('gwgs', models.IntegerField(null=True, verbose_name='岗位个数（个）')),
                ('fwzsz', models.IntegerField(null=True, verbose_name='社会工作服务站（室、中心）设置情况（个）')),
                ('wmq', models.IntegerField(null=True, verbose_name='虽未明确为社会工作岗位，但实际岗位职责包括社会工作的（个）')),
                ('shgzr', models.IntegerField(null=True, verbose_name='已取得社会工作学历学位、职业资格或培训证书，但未从事社会工作的（人）')),
                ('comments', models.TextField(null=True, verbose_name='备注说明')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('t4_type', models.IntegerField(choices=[(1, '民政'), (2, '公安（禁毒办）'), (3, '司法行政'), (4, '扶贫'), (5, '工会'), (6, '共青团'), (7, '综治'), (8, '教育'), (9, '人力社保'), (10, '卫生计生'), (11, '信访'), (12, '妇联'), (13, '残联')], null=True, verbose_name='类别')),
                ('rcsl', models.IntegerField(null=True, verbose_name='人才数量（人）')),
                ('shjzrq', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据截止日期')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('year_tag', models.CharField(choices=[('2017', '2017年社会工作培训情况')], max_length=8, null=True, verbose_name='统计年份')),
                ('pxrc', models.IntegerField(null=True, verbose_name='培训人次')),
                ('jqnzzl', models.IntegerField(null=True, verbose_name='较去年增长量')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '在省级民政部门登记的'), (2, '在地市级民政部门登记的'), (3, '在县区级民政部门登记的')], null=True, verbose_name='级别')),
                ('shgzhyxhgs', models.IntegerField(null=True, verbose_name='社会工作行业协会数量（个）')),
                ('cldzzsl', models.IntegerField(null=True, verbose_name='成立党组织数量（个）')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable7',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '省级民政部门登记的民办社会工作服务机构数量'), (2, '地市级民政部门登记的民办社会工作服务机构数量'), (3, '县区级民政部门登记的民办社会工作服务机构数量')], null=True, verbose_name='级别')),
                ('jgsl', models.IntegerField(null=True, verbose_name='机构数量（个）')),
                ('zzgzrysl', models.IntegerField(null=True, verbose_name='专职工作人员数量（人）')),
                ('jcdzzsl', models.IntegerField(null=True, verbose_name='机构中经过上级党组织批准设立的基层党组织数量（个）')),
                ('dysl', models.IntegerField(null=True, verbose_name='专职工作人员中的党员数量（人）')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable8',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('t8_type', models.IntegerField(choices=[(1, '本省范围财政性资金'), (2, '本省范围福利彩票公益金'), (3, '本省范围其他资金（请注明资金来源）'), (4, '“民政部本级彩票金社会工作和志愿服务项目”资金执行、结余情况及主要服务项目（活动）开展情况')], null=True, verbose_name='类别')),
                ('zjtrzl', models.IntegerField(null=True, verbose_name='2017年资金投入总量（万元）')),
                ('jsnzzl', models.IntegerField(null=True, verbose_name='较上年增长量（万元）')),
                ('comments', models.TextField(default='', verbose_name='本省范围其他资金，来源备注')),
                ('description', models.TextField(default='', verbose_name='“民政部本级彩票金社会工作和志愿服务项目”资金执行、结余情况及主要服务项目（活动）开展情况')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.CreateModel(
            name='SWTable9',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('t9_type', models.IntegerField(choices=[(1, '社会工作试点示范'), (2, '社会工作工程、计划、项目')], null=True, verbose_name='类别')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='名称')),
                ('zyqkjs', models.TextField(null=True, verbose_name='主要情况简介')),
                ('kzddqhdwmc', models.TextField(null=True, verbose_name='开展的地区和单位名称')),
                ('province', models.CharField(choices=[('Aomen', '澳门特别行政区'), ('Shanghai', '上海市'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Heilongjiang', '黑龙江省'), ('Hainan', '海南省'), ('Ningxia', '宁夏回族自治区'), ('Jiangxi', '江西省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Jilin', '吉林省'), ('ShanVxi', '陕西省'), ('Anhui', '安徽省'), ('Taiwan', '台湾省'), ('Shandong', '山东省'), ('Neimenggu', '内蒙古自治区'), ('Qinghai', '青海省'), ('Gansu', '甘肃省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Jiangsu', '江苏省'), ('Tianjin', '天津市'), ('Xianggang', '香港特别行政区'), ('Hebei', '河北省'), ('Xizhang', '西藏自治区'), ('Guizhou', '贵州省'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('Guangxi', '广西壮族自治区'), ('Shanxi', '山西省'), ('Zhejiang', '浙江省'), ('Henan', '河南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Sichuan', '四川省'), ('Fujian', '福建省'), ('Liaoning', '辽宁省')], max_length=32, null=True, verbose_name='数据所属省份')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
    ]
