# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swcworks_web', '0002_swtable1_swtable10_swtable11_swtable12_swtable13_swtable14_swtable15_swtable16_swtable17_swtable2_sw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swtable1',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable10',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable11',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable12',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable13',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable14',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable15',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable16',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable17',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable2',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable3',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable4',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable5',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable6',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable7',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable8',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable9',
            name='province',
            field=models.CharField(choices=[('Neimenggu', '内蒙古自治区'), ('Anhui', '安徽省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Heilongjiang', '黑龙江省'), ('Guizhou', '贵州省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Shanghai', '上海市'), ('Shandong', '山东省'), ('Hunan', '湖南省'), ('Hubei', '河北省'), ('Chongqing', '重庆市'), ('Jilin', '吉林省'), ('Henan', '河南省'), ('Fujian', '福建省'), ('Hebei', '河北省'), ('Hainan', '海南省'), ('Gansu', '甘肃省'), ('Beijing', '北京市'), ('Ningxia', '宁夏回族自治区'), ('Liaoning', '辽宁省'), ('Taiwan', '台湾省'), ('Jiangsu', '江苏省'), ('Guangdong', '广东省'), ('Shanxi', '山西省'), ('Yunnan', '云南省'), ('Aomen', '澳门特别行政区'), ('ShanVxi', '陕西省'), ('Tianjin', '天津市'), ('Zhejiang', '浙江省'), ('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Sichuan', '四川省'), ('Xianggang', '香港特别行政区')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
    ]
