# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swcworks_web', '0003_auto_20171223_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swtable1',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable10',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable11',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable12',
            name='bl',
            field=models.FloatField(null=True, verbose_name='注册志愿者占当地居民人口总数的比例（%）'),
        ),
        migrations.AlterField(
            model_name='swtable12',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable13',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable14',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable15',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable16',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable17',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable2',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable3',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable4',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable5',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable6',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable7',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable8',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable9',
            name='province',
            field=models.CharField(choices=[('Qinghai', '青海省'), ('Xizhang', '西藏自治区'), ('Aomen', '澳门特别行政区'), ('Hebei', '河北省'), ('Hubei', '河北省'), ('Zhejiang', '浙江省'), ('Jilin', '吉林省'), ('Shanghai', '上海市'), ('Ningxia', '宁夏回族自治区'), ('Anhui', '安徽省'), ('Hainan', '海南省'), ('Heilongjiang', '黑龙江省'), ('Yunnan', '云南省'), ('Hunan', '湖南省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Guizhou', '贵州省'), ('Fujian', '福建省'), ('Shandong', '山东省'), ('Sichuan', '四川省'), ('Guangxi', '广西壮族自治区'), ('Tianjin', '天津市'), ('Shanxi', '山西省'), ('Liaoning', '辽宁省'), ('Xianggang', '香港特别行政区'), ('Beijing', '北京市'), ('Guangdong', '广东省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Jiangsu', '江苏省'), ('Neimenggu', '内蒙古自治区'), ('Gansu', '甘肃省'), ('Chongqing', '重庆市'), ('Taiwan', '台湾省'), ('Jiangxi', '江西省'), ('ShanVxi', '陕西省'), ('Henan', '河南省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
    ]
