# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swcworks_web', '0004_auto_20171224_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swtable4',
            name='rcsl',
        ),
        migrations.RemoveField(
            model_name='swtable4',
            name='shjzrq',
        ),
        migrations.RemoveField(
            model_name='swtable4',
            name='t4_type',
        ),
        migrations.AddField(
            model_name='swtable4',
            name='canlian',
            field=models.IntegerField(default=0, verbose_name='残联'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='fulian',
            field=models.IntegerField(default=0, verbose_name='妇联'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='fupin',
            field=models.IntegerField(default=0, verbose_name='扶贫'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='gongan',
            field=models.IntegerField(default=0, verbose_name='公安（禁毒办）'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='gonghui',
            field=models.IntegerField(default=0, verbose_name='工会'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='gongqingtuan',
            field=models.IntegerField(default=0, verbose_name='共青团'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='jiaoyu',
            field=models.IntegerField(default=0, verbose_name='教育'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='minzheng',
            field=models.IntegerField(default=0, verbose_name='民政'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='renlishebao',
            field=models.IntegerField(default=0, verbose_name='人力社保'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='sifaxingzheng',
            field=models.IntegerField(default=0, verbose_name='司法行政'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='weishengjisheng',
            field=models.IntegerField(default=0, verbose_name='卫生计生'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='xinfang',
            field=models.IntegerField(default=0, verbose_name='信访'),
        ),
        migrations.AddField(
            model_name='swtable4',
            name='zongzhi',
            field=models.IntegerField(default=0, verbose_name='综治'),
        ),
        migrations.AlterField(
            model_name='swtable1',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable10',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable11',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable12',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable13',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable14',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable15',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable16',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable17',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable2',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable3',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable4',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable5',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable6',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable7',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable8',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable9',
            name='province',
            field=models.CharField(choices=[('Hubei', '河北省'), ('Beijing', '北京市'), ('Liaoning', '辽宁省'), ('Zhejiang', '浙江省'), ('Taiwan', '台湾省'), ('Yunnan', '云南省'), ('Heilongjiang', '黑龙江省'), ('XinjiangSCJSBT', '新疆生产建设兵团'), ('Xianggang', '香港特别行政区'), ('Guizhou', '贵州省'), ('Guangdong', '广东省'), ('Anhui', '安徽省'), ('Aomen', '澳门特别行政区'), ('Ningxia', '宁夏回族自治区'), ('Hebei', '河北省'), ('Tianjin', '天津市'), ('Chongqing', '重庆市'), ('Shandong', '山东省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Hainan', '海南省'), ('Guangxi', '广西壮族自治区'), ('Jiangxi', '江西省'), ('Xizhang', '西藏自治区'), ('Jiangsu', '江苏省'), ('Shanghai', '上海市'), ('Qinghai', '青海省'), ('Henan', '河南省'), ('ShanVxi', '陕西省'), ('Sichuan', '四川省'), ('Jilin', '吉林省'), ('Gansu', '甘肃省'), ('Fujian', '福建省'), ('Hunan', '湖南省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
    ]
