# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swcworks_web', '0005_auto_20171224_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='swtable11',
            name='sqtotalnum',
            field=models.IntegerField(null=True, verbose_name='社区内部成立的志愿服务队伍总数（个）'),
        ),
        migrations.AddField(
            model_name='swtable11',
            name='totalnum',
            field=models.IntegerField(null=True, verbose_name='全省社区志愿服务站点数（个）'),
        ),
        migrations.AddField(
            model_name='swtable13',
            name='fuwuzuzhitoalnum',
            field=models.IntegerField(null=True, verbose_name='志愿服务组织培训的志愿者总人数'),
        ),
        migrations.AddField(
            model_name='swtable13',
            name='jiguantotalnum',
            field=models.IntegerField(null=True, verbose_name='党政机关组织培训的志愿者总人数'),
        ),
        migrations.AddField(
            model_name='swtable13',
            name='othertotalnum',
            field=models.IntegerField(null=True, verbose_name='其他组织培训的志愿者总人数'),
        ),
        migrations.AddField(
            model_name='swtable13',
            name='totalnum',
            field=models.IntegerField(null=True, verbose_name='2018年全省范围内志愿者培训总人数'),
        ),
        migrations.AddField(
            model_name='swtable6',
            name='xiehuiorgnum',
            field=models.IntegerField(null=True, verbose_name='行业协会单位会员数量（个）'),
        ),
        migrations.AddField(
            model_name='swtable6',
            name='xiehuipernum',
            field=models.IntegerField(null=True, verbose_name='行业协会个人会员数量（个）'),
        ),
        migrations.AddField(
            model_name='swtable9',
            name='num',
            field=models.IntegerField(null=True, verbose_name='覆盖贫困地区县/村数量（个）'),
        ),
        migrations.AddField(
            model_name='swtable9',
            name='trzj',
            field=models.IntegerField(null=True, verbose_name='投入资金（万元）'),
        ),
        migrations.AlterField(
            model_name='swtable1',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable10',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable11',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable12',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable13',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable14',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable15',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable16',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable17',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable2',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable3',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable4',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable5',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable6',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable7',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable8',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
        migrations.AlterField(
            model_name='swtable9',
            name='province',
            field=models.CharField(choices=[('Beijing', '北京市'), ('Tianjin', '天津市'), ('Shanghai', '上海市'), ('Chongqing', '重庆市'), ('Heilongjiang', '黑龙江省'), ('Jilin', '吉林省'), ('Liaoning', '辽宁省'), ('Hebei', '河北省'), ('Neimenggu', '内蒙古自治区'), ('Shanxi', '山西省'), ('Shandong', '山东省'), ('Henan', '河南省'), ('Anhui', '安徽省'), ('Jiangsu', '江苏省'), ('Zhejiang', '浙江省'), ('Fujian', '福建省'), ('Jiangxi', '江西省'), ('Guangdong', '广东省'), ('Hubei', '湖北省'), ('Hunan', '湖南省'), ('Guangxi', '广西壮族自治区'), ('Hainan', '海南省'), ('Yunnan', '云南省'), ('Guizhou', '贵州省'), ('Sichuan', '四川省'), ('ShanVxi', '陕西省'), ('Ningxia', '宁夏回族自治区'), ('Gansu', '甘肃省'), ('Xizhang', '西藏自治区'), ('Qinghai', '青海省'), ('Xinjiang', '新疆维吾尔族自治区'), ('Xianggang', '香港特别行政区'), ('Aomen', '澳门特别行政区'), ('Taiwan', '台湾省'), ('XinjiangSCJSBT', '新疆生产建设兵团')], max_length=32, null=True, verbose_name='数据所属省份'),
        ),
    ]
