# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-02 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swcworks_web', '0007_auto_20190102_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swtable3',
            name='t3_type',
            field=models.IntegerField(choices=[(1, '乡镇、街道和社区'), (2, '民政事业单位'), (3, '其他系统事业单位'), (4, '社会组织'), (5, '其他（请在备注注明）')], null=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='swtable7',
            name='level',
            field=models.IntegerField(choices=[(1, '省级民政部门登记'), (2, '地市级民政部门登记'), (3, '县区级民政部门登记')], null=True, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='swtable8',
            name='t8_type',
            field=models.IntegerField(choices=[(1, '本省范围财政性资金'), (2, '本省范围福利彩票公益金'), (3, '本省范围其他资金'), (4, '“民政部本级彩票金社会工作和志愿服务项目”资金执行、结余情况及主要服务项目（活动）开展情况')], null=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='swtable9',
            name='t9_type',
            field=models.IntegerField(choices=[(1, '社会工作参与脱贫攻坚示范项目'), (2, '社会工作试点示范'), (3, '社会工作工程、计划、项目')], null=True, verbose_name='类别'),
        ),
    ]
