# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swcworks_web', '0008_auto_20190102_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWTable2For2019',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('jigou_type', models.CharField(default='', max_length=128, verbose_name='机构类别')),
                ('qitajigou_comment', models.TextField(default='', verbose_name='其他机构备注')),
                ('zongshu', models.IntegerField(default=0, verbose_name='机构总数量（个）')),
                ('szsgks', models.IntegerField(default=0, verbose_name='设置社工科（室）的机构数量（个）')),
                ('wszsgks', models.IntegerField(default=0, verbose_name='未设置社工科（室）但设有社工岗位的机构数量（个）')),
                ('sggw', models.IntegerField(default=0, verbose_name='社工岗位数量（个）')),
                ('province', models.CharField(choices=[('Beijing', '1、北京市'), ('Tianjin', '2、天津市'), ('Shanghai', '3、上海市'), ('Chongqing', '4、重庆市'), ('Heilongjiang', '5、黑龙江省'), ('Jilin', '6、吉林省'), ('Liaoning', '7、辽宁省'), ('Hebei', '8、河北省'), ('Neimenggu', '9、内蒙古自治区'), ('Shanxi', '10、山西省'), ('Shandong', '11、山东省'), ('Henan', '12、河南省'), ('Anhui', '13、安徽省'), ('Jiangsu', '14、江苏省'), ('Zhejiang', '15、浙江省'), ('Fujian', '16、福建省'), ('Jiangxi', '17、江西省'), ('Guangdong', '18、广东省'), ('Hubei', '19、湖北省'), ('Hunan', '20、湖南省'), ('Guangxi', '21、广西壮族自治区'), ('Hainan', '22、海南省'), ('Yunnan', '23、云南省'), ('Guizhou', '24、贵州省'), ('Sichuan', '25、四川省'), ('ShanVxi', '26、陕西省'), ('Ningxia', '27、宁夏回族自治区'), ('Gansu', '28、甘肃省'), ('Xizhang', '29、西藏自治区'), ('Qinghai', '30、青海省'), ('Xinjiang', '31、新疆维吾尔族自治区'), ('Xianggang', '32、香港特别行政区'), ('Aomen', '33、澳门特别行政区'), ('Taiwan', '34、台湾省'), ('XinjiangSCJSBT', '35、新疆生产建设兵团')], max_length=32, null=True, verbose_name='省（市、区）')),
                ('reporter', models.CharField(max_length=256, null=True, verbose_name='数据提交人')),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='数据提交时间')),
            ],
        ),
        migrations.AddField(
            model_name='swtable5',
            name='zheng_ti_gui_hua',
            field=models.TextField(default='', verbose_name='社会工作人才纳入本省（区市）人才培养整体规划情况:'),
        ),
    ]
